# Top-level makefile for Energia code
# Rod Price

ENERGIADIR := /opt/energia-1.6.10E18
ENERGIABOARD := MSP-EXP430G2553LP
# SOURCES := main.c other.cc
# LIBRARIES := EEPROM

include ~/working/balloon/radio/electronics/beacon/code/energia.mk
